### ISSUE TITLE
Can it be used in a browser?

### ISSUE THREAD

**Issue by roman-khazanskii** [grantila/awesome-ajv-errors#3]
I'd really like to use awesome-ajv-errors in browser but when I try to "just do it", I see this:

```
ERROR in ./node_modules/ansi-escapes/index.js 5:22-29
Module not found: Error: Can't resolve 'process/browser' in './node_modules/ansi-escapes'
```
Would be nice to get errors colored with CSS (or smthn, I dunno, I'm not a web-developer really :) or something less platform-specific..

**Comment by roman-khazanskii** [comment]
Well, I was able to 'ducktape' two env variables to webpack:
```js
    new webpack.DefinePlugin({
      'process.env.TERM_PROGRAM': JSON.stringify(process.env.TERM_PROGRAM),
      'process.platform': JSON.stringify(process.platform),
    }),
```
And afterwards it kinda works! Although I had to change the call:
from `prettify( validate, {input} )` to `prettify( validate, {data: input, colors: true} )`, otherwise some strange exception was raised about 'opts.data is undefined`.

Still no colors :( Despite `colors: true`.

Please bear in mind that I'm not a web-developer and I have very little idea of what I'm doing :) Very sorry if my questions are trivial!

**Comment by roman-khazanskii** [comment]
After some digging, I was able to determine that color support detection is made via [`supports-color` lib](https://github.com/chalk/supports-color). While it provides ways to force color with environment variable, that doesn't affect working in browser.

So I had to monkey-patch it with [`patch-package`](https://github.com/ds300/patch-package):
<details>

```diff
diff --git a/node_modules/supports-color/browser.js b/node_modules/supports-color/browser.js
index 62afa3a..a766564 100644
--- a/node_modules/supports-color/browser.js
+++ b/node_modules/supports-color/browser.js
@@ -1,5 +1,15 @@
 'use strict';
 module.exports = {
-	stdout: false,
-	stderr: false
+	stdout: {
+		level: 3,
+		hasBasic: true,
+		has256: true,
+		has16m: true
+	},
+	stderr: {
+		level: 3,
+		hasBasic: true,
+		has256: true,
+		has16m: true
+	}
 };
```

</details>

That got me ANSI-escaped colored string from `prettify`, which I was able to convert to HTML with [`ansi-to-html`](https://github.com/rburns/ansi-to-html).

(Funny enough, that colored string also worked in my browser console just fine :)

That was quite a jorney for me :) Sorry for my spamming in the issue like that, but I thought that it could be useful to somebody someday.

**Comment by grantila** [comment]
Good digging!

Converting colors to html works that way I guess, but it would also make sense to allow the browser console output to be nice, which works very differently.

I'll look into just dropping color support as a default for browsers instead. That could be added later, separately.

**Comment by roman-khazanskii** [comment]
>I'll look into just dropping color support as a default for browsers instead. That could be added later, separately.

Maybe instead consider adding an option to force colored output and let the user handle ansi-colored string? Since converting to html can easily be done by a separate lib.

**Comment by grantila** [comment]
Forcing colored output won't be possible without the hack you found, since `@babel/code-frame` uses very old versions of chalk and the underlying ansi packages. This is gonna be fixed in babel 8 it seems ([this](https://github.com/babel/babel/issues/14213) [was](https://github.com/babel/babel/issues/13728) [interesting](https://github.com/babel/babel/pull/13783)).

Until then, I've added separate export for browsers where colors and code-frame is by default turned off so that it loads without any issues (in a default setup of webpack at least). The readme explains how to work around this.

**Comment by roman-khazanskii** [comment]
Thank you! :tada:

**Comment by grantila** [comment]
FYI @roman-khazanskii, modern package.json exports is quite broken, a lot of things out there doesn't understand it, e.g. Jest. Had to revert that to allow for old-school deep-imports into `/dist/`.

Anyway, v4 has better control of what to enable/disable, check the bottom of the readme for configuring styling if you want to customize it.

**Comment by roman-khazanskii** [comment]
>FYI @roman-khazanskii, modern package.json exports is quite broken, a lot of things out there doesn't understand it, e.g. Jest. Had to revert that to allow for old-school deep-imports into /dist/.

Sorry, I'm afraid I don't follow :(

**Comment by grantila** [comment]
Never mind, just use v4, it should work fine
